version: '3.8'
services:

    mixupapi:
        build:
            context: ./MixUp
            dockerfile: MixUpAPI/Dockerfile
        depends_on:
            - dbmanager
        ports: 
            - "9000:80"
        links:
            - dbmanager
    
    dbmanager:
        build:
            context: ./MixUp
            dockerfile: DBManager/Dockerfile

    # Ngrok Service
    ngrok:
        image: shkoliar/ngrok:latest
        ports:
        - 4551:4551
        links:
        - mixupapi
        environment:
        - DOMAIN=mixupapi
        - PORT=80
        