version: '3.8'
services:

    mixupapi:
        build:
            context: ./MixUp
            dockerfile: MixUpAPI/Dockerfile
        depends_on:
            - dbmanager
        ports: 
            - "9000:80"
        links:
            - dbmanager
    
    dbmanager:
        build:
            context: ./MixUp
            dockerfile: DBManager/Dockerfile

# tunnel service to make our mixup API service expose to the internet
    localtunnel:
        image: efrecon/localtunnel
        links:
            - mixupapi
        command:
            --local-host mixupapi --port 80 --subdomain servermixupudes
        